config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :songs
  resources :artists
  post 'songs/upload', to: 'songs#upload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  def artist_name
    self.try(:artist).try(:name)
  end

  def artist_name=(name)
    artist = Artist.find_or_create_by(name: name)
    self.artist = artist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    @artist.update(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    flash[:notice] = "Artist deleted."
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  require 'csv'

  def upload
    CSV.foreach(params[:file].path, headers: true) do |song|
      Artist.find_or_create_by(name: song[1])
      Song.create(title: song[0], artist_id: song[1])
    end
    redirect_to songs_path
  end

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    @song.update(song_params)

    if @song.save
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "Song deleted."
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def display_artist(song)
    song.artist.nil? ? link_to("Add Artist", edit_song_path(song)) : link_to(song.artist_name, artist_path(song.artist))
  end
end

app/helpers/songs_helper.rb
module SongsHelper

end

app/views/artists/edit.html.erb
<h1>Editing <%= @artist.name %></h1>

<%= form_for @artist  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/artists/new.html.erb
<h1>Create an Artist</h1>

<%= form_for @artist  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatiron Tunes</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing <%= @song.name %></h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<ul>
<% @songs.each do |song| %>
  <li><%= display_artist(song) %> - <%= link_to song.title, song_path(song) %></li>
<% end %>
</ul>
<br>
<%= link_to "Add New Song", new_song_path %>

<%= form_tag songs_upload_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Songs" %>
<% end %>

app/views/songs/new.html.erb
<h1>Create a Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= link_to @song.title, song_path(@song) %></h1>
<h3> by <%= display_artist(@song) %></h3>

<%= link_to "All Songs", songs_path %>